version: "3.8"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    restart: always
    ports:
      - 9200:9200
    volumes:
      - C:/Users/Moch/.elk/esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
    restart: always
    ports:
      - 5601:5601